dist: trusty
language: rust
rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_script:
  - rustup component add clippy

script:
  - cargo build
  - cargo clippy -- -D warnings